namespace MAVLinkSDK.UI
{
    internal class __doc
    {
        // only contains constructs on old Unity UI.

        // for constructs on new UI toolkit, use Scripts.UIElements namespace

        // most content of this package is generated by Claude 3.5
    }
}